### ISSUE TITLE
Scrollbar is shown when it shouldn't

### ISSUE THREAD

**Issue by idoberko2** [guytepper/1km.co.il#11]
**Steps to reproduce:**
1. Open the app on an iPad / laptop (screen width > 768px)
1. Search for a place that shows only 1 protest
1. Examine at the protest list

**Expected result:**
Only 1 protest is found so there's no need to show a scroll bar.

**Actual result:**
A disabled scrollbar is presented:
![image](https://user-images.githubusercontent.com/6158608/94990669-9cd6a000-0586-11eb-972a-d305d14be1bf.png)

**Comment by idoberko2** [comment]
Fixed in https://github.com/guytepper/1km.co.il/pull/12

**Comment by guytepper** [comment]
Thanks for the detailed report and the fix 🙏

**Comment by idoberko2** [comment]
Verified:

No scroll bar:
![image](https://user-images.githubusercontent.com/6158608/95013496-4a11ec80-0649-11eb-81a8-5abb55efcd99.png)


With scroll bar:
![image](https://user-images.githubusercontent.com/6158608/95013468-28b10080-0649-11eb-88cd-143cefb3d9de.png)
