### ISSUE TITLE
Next Team Meeting - Discussion Ideas

### ISSUE THREAD

**Issue by guytepper** [guytepper/1km.co.il#115]
Instead of a private google doc, let's share what we plan to do with the world.
Here's the idea list I'll keep update as we get to the meeting itself:

Product & Development
- New version: current status, metrics & user feedback
 - Privacy: How we'll tackle privacy concerns in the product
- Ideas for this week and how to achieve them without stress. 
  - Allow people to check in to protests.
  - Create a check-in feed.
  - We want to make the protest page a "homepage" for the protest, that the protest attendees will check regularly and frequently - what should be done for better search engine indexing (@webernir suggests static pages).
- TypeScript #18 
- "Add Protest" page phase 2 - Improved UX of selecting more than one date.
- Zendesk integration - adding support chat.
- How to welcome new contributors to the team
- Moving from public user repo to organization -  pros & cons, how to do it properly

Project Spirit
- Manifesto discussion
- Donations overview
- Future plans (short, mid & long)

### Feel free to comment with subjects for discussion and I'll add them to the list.

**Comment by webernir** [comment]
Regarding SSR - It would be better to create static pages instead of SSR.
Let's have a session over this topic.

Protest page - How about adding a RSVP selection on each protest page? So
users can mark themselves as "Going". And we could display a counter.

Push notifications - need to define required flows.

**Comment by danaavrh** [comment]
- "Add Protest" page phase 2 - Improved UX of selecting more than one date. 
- Zendesk integration - adding support chat.

Lower priority
- Adding My account section - will include my editable protests & protests I joined
- About page - including "תמיכה בפרויקט" page
