### ISSUE TITLE
Date input collapses on iOS

### ISSUE THREAD

**Issue by guytepper** [guytepper/1km.co.il#116]
From `AddProtest` component:

<img alt="" width="320" src="https://user-images.githubusercontent.com/13344923/95667996-48c74f00-0b76-11eb-8847-c64d85f7a2b6.jpeg" />

**Comment by idanen** [comment]
On which iOS doesn't this work? Or is it resolved by someone?

**Comment by guytepper** [comment]
Seems like it was fixed via https://github.com/guytepper/1km.co.il/commit/023acf2e2a34ab71ab2bcd13de297590143c5d96 (setting a default value for the element resolved this)
