### ISSUE TITLE
Add cancel button to edit protest page

### ISSUE THREAD

**Issue by joeyede** [guytepper/1km.co.il#127]
It would be much more elegent to have a button to allow you to cancel rather then just aborting mid edit if you change your mind.

**Comment by guytepper** [comment]
@joeyede Do you mean a button that acts like a 'back' button?

**Comment by joeyede** [comment]
yup.  with clear message on edits will be lost. 
It's not clear that the way to change your mind about editing is use the back button.  People are used to a cancel option

**Comment by CiTRuS93** [comment]
Hey can I this? and if I can, what should be the text for the message?

**Comment by guytepper** [comment]
Hey @CiTRuS93, sure, it's yours :)
Let's use `ביטול` for the text.

**Comment by CiTRuS93** [comment]
@guytepper 
I was talking about confirmation massage, something like "edits will be lost"

**Comment by guytepper** [comment]
Let's avoid the confirmation message for now.
