### ISSUE TITLE
Automate deployment

### ISSUE THREAD

**Issue by joeyede** [guytepper/1km.co.il#141]
CI!

**Comment by guytepper** [comment]
How to: https://firebase.google.com/docs/firestore/solutions/schedule-export#gcp-console

**Comment by joeyede** [comment]
We should enable automated deployment after pushing to master.

**Comment by guytepper** [comment]
Taking care of this now using https://firebase.google.com/docs/hosting/test-preview-deploy

**Comment by guytepper** [comment]
Resolved via https://github.com/guytepper/1km.co.il/commit/7ac08fc10a3d27e3f32bc0e625ec5f5bdba7fbde
