### ISSUE TITLE
Add flags marker cluster

### ISSUE THREAD

**Issue by guytepper** [guytepper/1km.co.il#15]
Too many flags are great in real life - but for the UI it can be a bit messy.
We can use [`react-leaflet-markercluster`](https://github.com/YUzhva/react-leaflet-markercluster) to fix this.

I'm not sure about how to display it. Some options in my mind:
1. Showing the number of flags.
2. Create a marker icon that shows a couple of flags together, depends on the  amount of flags in the area.

I'm in favor for the 2nd option but let me know if you think otherwise.

Implementation will possibly be related to [those lines](https://github.com/guytepper/1km.co.il/blob/master/src/components/Map/Map.js#L39-L42) in the `Map` component.

**Comment by daganomri** [comment]
I think we could get away with a custom icon for 2-4 flags, but for more than that the icon will get cluttered and an icon with a counter will be ideal.

**Comment by guytepper** [comment]
What do you mean by cluttered? pixelated, or too big and messy?

**Comment by daganomri** [comment]
I mean, how can you show five flags in a tiny SVG? The icon will be incomprehensible. I think 1-4 should have individual icons and 5 and up will have a counter
