### ISSUE TITLE
Create a refresh button to display address change modal

### ISSUE THREAD

**Issue by guytepper** [guytepper/1km.co.il#16]
As suggested by @UriGrod in https://github.com/guytepper/1km.co.il/issues/5#issuecomment-703064389, we can temporarily fix #7 by using a refresh button on top of the protest list to allow changing the address.

Try using the `Button` component for this. Button title should be 'שינוי כתובת'.

**Comment by daganomri** [comment]
I'd love to have a go at it. Is there an easier way to set up the environment than what's mentioned in the Readme?

**Comment by urish** [comment]
@daganomri are you on it?

**Comment by daganomri** [comment]
From initial inspection it seems that a simple refresh won't solve the problem. If you find a solution you can go ahead and take this

**Comment by urish** [comment]
Are you sure about that? When I refresh the page I do see the address popup coming back at me

**Comment by urish** [comment]
This can probably be closed

**Comment by guytepper** [comment]
Solved via #20
