### ISSUE TITLE
2nd Week Roadmap - New Features & Discussion

### ISSUE THREAD

**Issue by guytepper** [guytepper/1km.co.il#17]
# 2nd Week Roadmap
> [Read first: 1km - update about the first weekend and future plans](https://1km.co.il/project-updates/1)

Hi everyone. Thanks for all the responses and the will to contribute. I appreciate it a lot.
I'm handling all aspects of the project currently which is very time consuming, so I'd appreciate any help, mainly with the project development. 

The plan is to ship the following features by Thursday this week. 

## Dedicated protest Page
- Address & Map
- WhatsApp / Telegram / Facebook groups
- Next demonstration time(s)
- The option to upload photos (& videos?)

## Protest Organizer Dashboard
- An option to promote users to be protest organizers and edit the above details.
- Should be in the same view as the dedicated protest page.

## Admin Dashboard
- A 'super-admin' dashboard, allowing (non tech) contributors to filter protests, approve & edit them & manage protest organizers.

### Open Ideas 
- Photo gallery displaying photos nationwide protest photos.
- An option to add a live broadcast to a protest, and a page to display all live broadcasts (credit goes to Etay T [pending for github username] for the idea)

---
Please share any thoughts or ideas related to these features. Issues will be open for them soon.  
If there's a specific feature you want to take responsibility for, let me know.

Let's make it happen 💫

**Comment by uriklar** [comment]
@guytepper Do we have any mocks/designs for these features?

**Comment by guytepper** [comment]
@uriklar Not yet. I'll make the designs for all views tomorrow morning.

**Comment by UriGrod** [comment]
Expanding the Maavak with a couple of small features:

There are many organizations willing to participate. Having your own flag colour option, together with putting the Description front and centre, may help other groups that aren't currently in the streets to
