### ISSUE TITLE
Add loading spinner while fetching protests in ProtestSelection

### ISSUE THREAD

**Issue by guytepper** [guytepper/1km.co.il#182]
Add a loading spinner while fetching protests in `ProtestSelection` component.

The loading spinner is exists in `/icons/loading-spinner.svg`. It's being used widely across the code base - might be a good time to create a component for it.

<a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/13344923/97944704-04525c00-1d8e-11eb-87dc-69438e895b8a.gif">where it should be placed</a>

**Comment by almogbhl** [comment]
@guytepper  can I take this?

**Comment by guytepper** [comment]
@almogbhl sure! it's yours :)
If you need help with setting up the project, you can reach me through our [discord channel](https://discord.gg/VuzxwKN)
