### ISSUE TITLE
Create protest albums per date

### ISSUE THREAD

**Issue by guytepper** [guytepper/1km.co.il#185]
**How it works now:**
Currently, in the protest page, we show the 6 last pictures uploaded to it. 
When a visitor clicks the `לצפייה בגלריית ההפגנה` button, they see a list with _all_ the pictures uploaded the protest.

**What needs to be changed:**
Instead of showing all the pictures, we should show the picture galleries, sorted by dates. 
Here's a rough design for the galleries:

![Screen Shot 2020-11-05 at 12 32 22](https://user-images.githubusercontent.com/13344923/98229739-f6096900-1f62-11eb-9ae7-b1f06854953a.png)
On mobile you can change it to be 2 in a row, but feel free to play with it and change the design as you like it.

**How to approach:**
The `PictureGallery` component currently fetches & shows all the picture. 
It needs to be changed so it'll fetch one picture, the first one taken, per date. (I guess the component name needs to be changed too).

Pictures are being saved in the database inside the `pictures` collection. Each picture holds a `protestId` field and a `date` field. 

After you'll fetch a picture for each date, you need to create a new component & route for the gallery itself. 
Inside it, you should fetch all the pictures for the specified `date` & `protestId`, and show them like the pictures are being shown at the moment.

**Comment by MSanbira** [comment]
on it
