### ISSUE TITLE
Style AddressBar's focus ring on Android

### ISSUE THREAD

**Issue by guytepper** [guytepper/1km.co.il#195]
That's how the `AddressBar` focus ring looks on android chrome ([`ProtestMap`](https://1km.co.il/map) page)
![IMAGE 2020-11-07 10:31:39](https://user-images.githubusercontent.com/13344923/98436508-73a8b280-20e4-11eb-81a9-465ff549feb9.jpg)

This is how it looks on iOS Safari:
![IMAGE 2020-11-07 10:30:28](https://user-images.githubusercontent.com/13344923/98436521-a783d800-20e4-11eb-8919-5a834a3bbb8f.jpg)

We want to improve the looks of the Chrome focus ring so it'll match Safari's design.

### How to approach:
You need to change the `ComboboxInputWrapper` `:focus` styles. 
- Remove the current styles so it'll look the same on iOS & Android.
- Apply `box-shadow` and try to mimick the iOS focus. 
- Try to use `#7785fc` or `#b8c0fc` as the shadow colors - but if it doesn't looks nice, keep the original iOS color :)

**Comment by omri08** [comment]
Can I work on this one? :D

**Comment by guytepper** [comment]
@omri08 sure! it's all yours :]
