### ISSUE TITLE
Display loading spinner while ProtestPage is loading

### ISSUE THREAD

**Issue by guytepper** [guytepper/1km.co.il#198]
When the protest page is loading, the following indicator is being shown:

<img width="446" alt="Screen Shot 2020-11-08 at 10 16 15" src="https://user-images.githubusercontent.com/13344923/98460276-a8337180-21ab-11eb-80c4-705b6b46e669.png">

Let's make it look nicer with the [`LoadingSpinner`](https://github.com/guytepper/1km.co.il/blob/master/src/components/LoadingSpinner/LoadingSpinner.js) component.

## 🧐 How to approach:
- Locate the loading indicator on the [`ProtestPage`](https://github.com/guytepper/1km.co.il/blob/master/src/views/ProtestPage.js) component
- Change it to show a `<LoadingSpinner />`

**Comment by CiTRuS93** [comment]
can I have this?

**Comment by guytepper** [comment]
@CiTRuS93 sure! it's yours :)
