### ISSUE TITLE
Upload user picture to Firebase Storage on account creation

### ISSUE THREAD

**Issue by guytepper** [guytepper/1km.co.il#200]
When we save the user in Firestore, we also save the user picture to Firebase Storage.
We do this because content blockers block Facebook URLs - resulting in the profile picture not showing up. When we serve the picture from our own servers, it works fine.

Currently, we do this in the front end, but it'd more efficient and clean to move this code to a cloud function which would be triggered on account creation.

## 🧐 How to approach:
- Check out how we currently handle this flow in the [`saveUserInFirestore`](https://github.com/guytepper/1km.co.il/blob/master/src/api/index.js#L162-L202) method.
The method's code is cumbersome and deserves a refactor 🤓
- In order to develop with firebase cloud functions, [get yourself an emulator](https://firebase.google.com/docs/emulator-suite) which will make the process much easier.
If you need access to our firebase dev project - let me know via discord.
- Check out the docs on [authentication triggres](https://cloud.google.com/functions/docs/calling/firebase-auth).

**Comment by omri08** [comment]
After talking with @guytepper  I will take this one :)
