### ISSUE TITLE
Ask for user location on map initial load

### ISSUE THREAD

**Issue by guytepper** [guytepper/1km.co.il#201]
When a user visits the protest map and doesn't have their location cached, we want to get their GPS coordinates.

## 🧐 How to approach:
- The protest map is located in the [`ProtestMap`](https://github.com/guytepper/1km.co.il/blob/master/src/views/ProtestMap/ProtestMap.js) component.
- Check if `userCoordinates` exists in the store - if not ask for the user location using [`getCurrentPosition`](https://github.com/guytepper/1km.co.il/blob/master/src/utils.js#L4-L15). 
- Update the user coordinates in the store, and the protests should be fetched automatically through [the effect in `ProtestMap`](https://github.com/guytepper/1km.co.il/blob/master/src/views/ProtestMap/ProtestMap.js#L23-L29).

**Comment by omri08** [comment]
Can I work on this one?

**Comment by guytepper** [comment]
@omri08 sure! it's yours :)
