### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by guytepper** [guytepper/1km.co.il#22]
Hi folks, 

I'm overwhelmed by the community response to help with the project. Thank you, I appreciate it a lot.

I didn't expect the project to get to where it is right now - and I need to ask for help in order to make the project achieve it's goals. 
Currently, I'm responsible for all aspects of the project - some of it includes supporting users, approving & editing protests, creating a [non-tech] contribution infrastructure and getting in touch with organizations. 
It's hard for me to maintain the development aspect while being in this position. 

I'm looking for people who have time and feel they can help me maintain the project in the upcoming weeks. 
If you feel you can take this position, let me know.

Cheers,
Guy

**Comment by urish** [comment]
@dafnamordechai maybe someone from Baot would be open to help here?

**Comment by joeyede** [comment]
@guytepper I would be happy to help let me know what I can do.   I am guessing you are pretty overwhelmed but if you want effective help you need to be specific.  Break down the work that needs to be done and divide that up between willing volunteers.

**Comment by guytepper** [comment]
Hei  @joeyede, thanks a lot for willing to help. 
I'm looking for someone with similar responsibilities to a team leader. Needs to know how to take the roadmap & translate it into issues for contributors, review PRs, etc.

**Comment by urish** [comment]
I suggest to also put a note at the top of the README (and link to this issue). Here is [an example](https://github.com/urish/angular-spinner/commit/2ada79bfd8e0ea19434079772a038fe99a9f730a#diff-04c6e90faac2675aa89e2176d2eec7d8).

**Comment by joeyede** [comment]
I probably can do that.
Want to jump on a quick video call?

**Comment by guytepper** [comment]
@joeyede send me an email with your phone number - guytepper@protonmail.com

**Comment by guytepper** [comment]
@uriklar joined as a maintainer! We'd love more help :-)

**Comment by webernir** [comment]
I would like to join a maintainer as well @guytepper

**Comment by guytepper** [comment]
@webernir is now a maintainer! Congratulations! 🥳

Still looking for more help. Let me know if you'd like to join us!

**Comment by guytepper** [comment]
Seems like we're doing fine now :) Thanks everyone ❣️
