### ISSUE TITLE
Protest dates field modeling

### ISSUE THREAD

**Issue by guytepper** [guytepper/1km.co.il#24]
The most requested feature is to allow protest managers to update the upcoming protest dates. 
We currently rely on them adding it to the protest notes.

The 3 options in my mind for providing the dates:
* **Recurring:** Showing Sun-Sat dates, with hours for each date, and let them check on what day & time they will protest.
* **Specific:** Add a specific date & time for each protest.
* **Both:** Provide the option for both recurring and specific dates.

Personally I think that the 3rd option is the best, in case it won't be drastically harder to implement.

**For discussion:**
- How should we model each use case?
- How should we combine them together, in case we go with the 3rd way?

**Comment by markVaykhansky** [comment]
I'd also go with option #3. 
Something like:
`interface ProtestDate {`
`    initialDate: Date;`
`    repeatRate: 'day' | 'week' | 'month'; `
`}`

**Comment by guytepper** [comment]
@markVaykhansky great, i think that's the way we'll go. thanks!

@uriklar what's your opinion?

**Comment by uriklar** [comment]
I think the suggestion made here is a bit overly complex. 

Also, IMHO both specific and recurring  dates might be a bit complex from  a UX (and a dev) perspective.

Id go for either specific dates or recurring. And the specific will be an array of dates. We should probably also save a date_type field so they can toggle between the options without loosing previous data.

**Comment by webernir** [comment]
I agree with @uriklar about the complexity. 
I would add array of specific dates. so each "protest manager" can define the dates of which upcoming protests are schedules. 
This has 2 upsides:
- If you look at the current state of protests around the country, many of them are spontaneous and not really happen on pre-defined recurring date/time.
- simple to implement
