### ISSUE TITLE
add multilanguage support

### ISSUE THREAD

**Issue by omrikiei** [guytepper/1km.co.il#25]
make this app accessible to all Israeli official languages(Hebrew, English, Russian, Arabic).

**Comment by yaron1m** [comment]
I can take this

**Comment by guytepper** [comment]
@yaron1m Go for it! How do you plan to implement it?

Apart from the UI, we need to discuss how we keep protest information, which is are all stored in one field for each detail in the database - do we want to create an option to store multiple language, or just keep using one language for now?

**Comment by yaron1m** [comment]
Let's start with enabling multiple languages in the app (without the data from DB). Then let's decide on the DB.

I have done something similar before, I am going to use `i18n-js` library that accepts json translation files.
