### ISSUE TITLE
Add terms of usage + Post component

### ISSUE THREAD

**Issue by guytepper** [guytepper/1km.co.il#26]
We were suggested by a lawyer to add the following הבהרה משפטית:

```
להלן הבהרה משפטית חשובה: 

1. אתר זה נבנה בהתנדבות ומתוך רצון לסייע לאזרחים לממש את זכות היסוד החוקתית שלהם להפגין למען המשטר הדמוקרטי ושלטון החוק. 

2. אתר זה נועד לסייע לאזרחים להפגין תוך שמירה על החוק ועל תקנת איסור הפגנה מעבר למתחם קילומטר אחד מהבית. 

3. בוני האתר ומפעיליו אינם אחראים משפטית לשום נזק או פגיעה שייגרמו למפגין שאינו שומר על הכללים ועל הוראות החוק והתקנות. 

4. אנו קוראים לכל המפגינים והמפגינות לפעול אך ורק בהתאם לחוק ולתקנות ולכללי הזהירות הרפואית.
```

It's a good chance to create a `Post` component, and a posts folder under views. 
We should be able to provide markdown to generate new pages. You can take the styles from [update page](https://github.com/guytepper/1km.co.il/blob/master/src/views/ProjectUpdates/index.js).

You can remove the GitHub icon from the footer and place the link on the other side. It should be smallest as possible for the human eye to notice.

**Comment by daganomri** [comment]
Could we maybe incorporate something like MDX for the posts? Seems simpler than writing posts as html pages.

**Comment by urish** [comment]
> It should be smallest as possible for the human eye to notice.

Then why bother?

**Comment by daganomri** [comment]
I'd love to take this. I'll work on it tonight.

**Comment by guytepper** [comment]
@urish talking about 14px~. Visible but not grabbing attention.
