### ISSUE TITLE
Replace recaptcha v3 with v2

### ISSUE THREAD

**Issue by uriklar** [guytepper/1km.co.il#36]
Implement recaptcha v2 in the `ProtestForm`.

Currently recaptcha v3 is commented out since it rejected 50% of the users.
The recaptcha API (using  `react-recaptcha-v3`) is commented out in the `api` file and in `ProtestForm`,

**Comment by webernir** [comment]
Anyone working on that @guytepper ?

**Comment by guytepper** [comment]
@webernir negative. wanna take this?

**Comment by webernir** [comment]
Yes. On it..
