### ISSUE TITLE
Roadmap? :)

### ISSUE THREAD

**Issue by dotansimha** [guytepper/1km.co.il#4]
Hi @guytepper ! 

Is there a list of features or a short roadmap for this project?  

Me and [our team of developers](http://the-guild.dev/) would love to help you with that project, in any way.

Let me know / assign me to issues if you need any help! :)

**Comment by guytepper** [comment]
Hi Dotan! 
I'll sort out things tomorrow- set up the installation instructions and open some issues for grabs.

Thanks for reaching out! I'll let you know once it's ready. 🙂

**Comment by idoberko2** [comment]
+1 on that

**Comment by hpsharon** [comment]
+1

**Comment by guytepper** [comment]
Thanks everyone, preparing instructions & issues now. Will be ready in 1-2 hours.

**Comment by guytepper** [comment]
The README has been updated, and a [discord server](https://discord.gg/P8uSsrR) is now live.
Keep an eye on the issues tab, new issues are on the way :-)

**Comment by uriklar** [comment]
@guytepper +1
Feel free to assign any issue on me I'd be happy to contribute.

**Comment by dotansimha** [comment]
Awesome! Thank you @guytepper ! I'll be able to able during this week. 
I saw you added issues and upcoming tasks, so I'm closing this one. Thank you!
