### ISSUE TITLE
Autofocus address input on render

### ISSUE THREAD

**Issue by guytepper** [guytepper/1km.co.il#40]
Autofocus the address input when it gets rendered. 
Simply adding `autoFocus` to the element won't work, probably because of `react-modal` which takes control of the focus state in the modal.

<img width="300" alt="Screen Shot 2020-10-06 at 9 37 33" src="https://user-images.githubusercontent.com/13344923/95167185-dd693000-07b7-11eb-84ec-316829f0afba.png">

**Comment by urish** [comment]
On it.
