### ISSUE TITLE
Super Admin Page

### ISSUE THREAD

**Issue by guytepper** [guytepper/1km.co.il#46]
- Table that display all protests.
- Filter for Approved / Not Approved protests. 
- When viewing any of them, the Protest Page opens.

Adding the approve & edit functionality will be handled in a separate PR.

I'll provide the design soon

**Comment by daganomri** [comment]
I'll take this

**Comment by guytepper** [comment]
That's how `Admin.js` page looks like right now:
![Screen_Shot_2020-10-06_at_14 47 03](https://user-images.githubusercontent.com/13344923/95198703-50889b80-07e4-11eb-8652-90a10f7c75c3.png)


Let's start with sidebar requirements:
- Sidebar shouldn't show protests initially, only by search
- Add autocomplete input (`PlacesAutocomplete`) to search for protests by address. Should fetch protests within 2km radius.
- Add option to filter approved / pending protests
- Clicking on a protest card should open it inside left window.

**Comment by webernir** [comment]
need help with the super admin?

**Comment by daganomri** [comment]
We can close this.
