### ISSUE TITLE
When accessed from laptop/desktop, I get location of internet supplier

### ISSUE THREAD

**Issue by UriGrod** [guytepper/1km.co.il#5]
In itself this is understandable. but maybe the ability then to go directly to a location would help. Probably a huge feature in itself...

Wonderful initiative BTW. Being able to access the Whatsapp Group from the map / add it (for Whatsapp Admins of points) will be a huge help.

**Comment by UriGrod** [comment]
For now even a button to "change address" which will do nothing but refresh the page, would already be a workaround.

**Comment by guytepper** [comment]
Resolved - there's a button to change the address :)
