### ISSUE TITLE
Update licence info ASAP

### ISSUE THREAD

**Issue by medic17** [guytepper/1km.co.il#50]
I know you are doing rapid prototyping but thought I should point something out. Although your project is Open Source, currently each code contributor (of ANY code) still holds full copyright to it. This means that no code can be legally forked and used in any other project. Also if you manage to make this a viable project that makes money they may want some of that in the future.

For the good of the project I suggest you implement one of the varies Open Source licences available at the [Open Source Initiative](https://opensource.org). Note, for this to be legally binding you must receive authorization in writing from all authors who you ended up using their code in your project. Every day that goes by will make this more difficult for you in the future.

You may find https://choosealicense.com useful in deciding which one to use.

I am willing to help you coordinate this if you wish

**Comment by urish** [comment]
While I personally prefer the MIT license, I declare all my contributions to this project (#20, #47) copyleft / public domain.
Meaning you can choose any license (even not open-source one), and I'll be good with it.

**Comment by guytepper** [comment]
Hi @medic17, any chance you can hop in to our discord so we can chat about this?

**Comment by guytepper** [comment]
Added MIT license. Thanks for the heads up!

**Comment by medic17** [comment]
sure I can discord if you like just give me a link @guytepper
