### ISSUE TITLE
Google Places Autocomplete & Geocode alternative

### ISSUE THREAD

**Issue by guytepper** [guytepper/1km.co.il#6]
[The prices for those APIs are tremendously high](https://cloud.google.com/maps-platform/pricing), at least for our current requests amount.  

Does anyone know a good API for autocomplete Israeli addresses, preferably with love for open source projects?

**Comment by urish** [comment]
Perhaps @kaplanlior or @oferb (who built [israelcoronamap](https://github.com/oferb/israelcoronamap)) can give a hint here

**Comment by guytepper** [comment]
I've scheduled a call with @kaplanlior tomorrow morning 😊

**Comment by oferb** [comment]
OpenStreetMap may have that data, because it shows up on the map:
https://www.openstreetmap.org/#map=12/31.8971/34.8143

I don't have any details about an API though.

Indeed @kaplanlior is a good guy to talk to :)

**Comment by idanmiara** [comment]
Hi,
[Nominatim](https://nominatim.openstreetmap.org/ui/search.html) is the open source alternative based on Open Street Map for geo-coding and reverse-geocoding.

I don't know if you might use the official OSM Nominatim server or you have to deploy you own.
If you do need to setup your own - I was able to easily deploy an OSM server on Ubuntu Docker using:
[mediagis/nominatim-docker](https://github.com/mediagis/nominatim-docker)
Deploying the server with the Israel data only takes just a few minutes.

[I wrote a shell script](https://github.com/talos-gis/osm-dockers) that downloads the OSM raw data and deploys a Nominatim Server and an OSM Tile Server (which I guess you don't need as you could use the official OSM Tile Server).

I didn't have the chance to use the Nominatim Server apart from testing that it works using the built-in web interface which looks exactly the same as in the [official Nominatim webpage](https://nominatim.openstreetmap.org/ui/search.html).

**Comment by imbenrabi** [comment]
Hi gents.
I think mapbox (https://docs.mapbox.com/api/), covers the necessities for this project tech and language-wise(geocoding, autocomplete, wide language support(including HE), IL data).
I used their solution for a small project before and was very pleased.

Unsure what scales are we talking about here, but they are proclaiming themselves as an open-source and community projects lovers. 

If you like the docs, let me know and I'll approach to see what we can get out of them and implement the integration.

**Comment by guytepper** [comment]
Hi @idanmiara @imbenrabi - I'll try to look into it tomorrow, but it's hard for me to dwell into pros and cons for each solution right now. Seems like Mapbox is more easy to implement though?

We currently have 170,000 Autocomplete API hits for the for the last 4 days, which translates to 1500nis. 

@imbenrabi have you used Mapbox for a project with Israeli addresses?
