### ISSUE TITLE
Protest Admin (Users, Roles and permissions)

### ISSUE THREAD

**Issue by ranyitz** [guytepper/1km.co.il#70]
This is a summary of the origina idea presented by @guytepper 

## Why do we need this?
We want each protest to have an admin that can modify its location, update the whatapp group and maybe do more things in the future. In general this will let us create another circle of people that can help with moderating.

## Sign up Flow
* From Protest Page, users will be able to press on a "Claim ownership" button that will redirect them to a sign up page.

* Because we now need the admin role for a specific person on a specific protest we first need to create this user, we'll user facebook auth in order to get the user details, there will be a "sign up using facebook" button. 

* After the user signs up using facebook, we're going to save its data on firestore (DB) based on the user id given by facebook login. We'll also need to add the information of which protest this user has admin on.  The protest id will be passed as a query parameter to the sign-up page, we'll assign the role of `admin` for this user on this protest. (At the moment this will be the only way to get an admin on a protest, in the future we'll may create a flow for claming protests for signed in users) 

* Before we finish with the registration, we're going to ask the user to add its phone number which we're going to use in case we want to verify this person identity.

* The user is now signed in, and being redirected to the "complete sign up" page where he/she can go back to the home page.

## Returning user

* We'll need to add a "login" button for already registered users that want to modify a protest which they are the admin on.

**Comment by daganomri** [comment]
I think we can close this issue, right?
