### ISSUE TITLE
Enforce valid URL on group links input

### ISSUE THREAD

**Issue by guytepper** [guytepper/1km.co.il#86]
Apparently many people are putting there invalid URLs (e.g. with text).

**Comment by urigat** [comment]
@webernir @guytepper, Done.
https://github.com/guytepper/1km.co.il/pull/113

**Comment by urigat** [comment]
@webernir , should we check specifically URLs for Whatsapp and telegram?

**Comment by webernir** [comment]
@urigat the issue reported was about invalid URLs ("...with text") so it is now merged and closed.
@guytepper if you want to explicitly check for whatsapp/telegram URLs please reopen and update the requirement.
