### ISSUE TITLE
AddProtest Map is behaving incorrectly when zooming 

### ISSUE THREAD

**Issue by guytepper** [guytepper/1km.co.il#9]
Probably related to the map's [static zoom level](https://github.com/guytepper/1km.co.il/blob/master/src/components/ProtestForm/ProtestForm.js#L86) and `onMove` handler messing up with each other.

<img src="https://user-images.githubusercontent.com/13344923/94983229-63337400-0549-11eb-8fdc-67132b472716.gif" width="225" />

**Comment by hpsharon** [comment]
Fix available at https://github.com/guytepper/1km.co.il/pull/10
